
---
output: 
  html_document:
  pdf_document: default
  word_document: default
title: "Assignment 11: Predictive Modeling - Part 2"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
```


-------

1. Install the package `mlbench` and use the follows to import the data

```{r}
library(mlbench)
data(PimaIndiansDiabetes)
df <- PimaIndiansDiabetes

head(df)
```

- Set seed to be 2020. 
- The target variable is `diabetes`
- Partition the data into 80% training and 20% testing.  

```{r}
names(df)[9] <- 'target'

library(caret)
set.seed(2020)
splitIndex <- createDataPartition(df$target, p = .80, 
                                  list = FALSE)
df_train <- df[ splitIndex,]
df_test <- df[-splitIndex,]
```


-------

2. Tuning Decision Tree:  Use cross-validation with 10 k-folds to find the maxdepth with the greatest accuracy. Plot the accuracy associated with different maxdepths against the maxdepths. The range to search for maxdepth is from 1 to 10. 

```{r}
# Decide the range of the maxdepth to search for the best
tuneGrid = expand.grid(maxdepth = 1:10)
# Tell caret to do Approach 2, i.e. Cross-Validation
trControl = trainControl(method = "cv",
                         number = 10)
# Do Approach 2 
tree_approach2 <- train(target~., data=df_train, 
                                method = "rpart2", 
                                trControl = trControl,
                                tuneGrid = tuneGrid)

# Plot the results
plot(tree_approach2)
```


-------

3. Make the final decision to select the maxdepth for your decision tree.  Is your selected maxdepth the same as the maxdepth found in 2?

```{r}
library(rpart)
tree1<-rpart(target ~ ., 
            data = df_train,
            control=rpart.control(maxdepth=1))

library(rattle)
fancyRpartPlot(tree1)

```


-------

4. Calculate the accuracy of your decision tree (the decision tree with your selected maxdepth in 3) on the test data. 

```{r}
pred <- predict(tree_approach2, df_test)
cm <- confusionMatrix(data = pred, reference = df_test$target, positive = "pos")
cm$overall[1]
```

